title: Jamie Tanna | Developer
title_short: Jamie Tanna
email: hi@jamietanna.co.uk
description: > # this means to ignore newlines until "baseurl:"
    The personal website for Jamie Tanna, a software developer from London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jamietanna
github_username:  jamietanna

# Build settings
markdown: kramdown

kramdown:
    input: GFM

sass:
    # sass_dir: assets/sass

exclude: ['Gemfile', 'Gemfile.lock', 'Capfile', 'config', 'lib', 'vendor', 'LICENSE.*', 'README.txt', TODO]
