name: Jamie Tanna
title: Jamie Tanna | Software Engineer
title_short: Jamie Tanna
email: hi@jamietanna.co.uk
image:
  src: profile.png
  alt: Me at Hack24
description: >
    The personal website for Jamie Tanna, a Software Engineer based in Nottingham.
long_description: >
  I'm a Software Engineer with a passion for backend engineering, especially with regard to APIs and automation. I've recently been gaining a hands-on experience of DevOps culture and practices, and use my site as a method of blogging about my learnings, as well as sharing information about projects I have previously, or are currently, working on in my spare time.
baseurl: ""
url: ""
username: jamietanna
author:
  fullname: Jamie Tanna
  gitlab: jamietanna
  github: jamietanna
  twitter: jamietanna

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      toc: true

collections:
  projects:
    output: true
  talks:
    output: true

category_title_prefix: 'Category: '
tag_title_prefix: 'Tag: '

exclude:
- Gemfile
- Gemfile.lock
- Capfile
- config
- lib
- vendor
- LICENSE.*
- README.txt
- TODO
- tmp
- node_modules
- gulpfile.js
- package.json
- README.md
- elements.html
- builder
- Dockerfile
- src
- log
- get_pr.py
- tags

gems:
  - jekyll-seo-tag
  - jekyll-git_metadata
  - jekyll-toc
