title: Jamie Tanna | Developer
title_short: Jamie Tanna
email: hi@jamietanna.co.uk
description: >
    The personal website for Jamie Tanna, a software developer from London.
baseurl: ""
url: ""
twitter_username: jamietanna
github_username:  jamietanna

markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- Capfile
- config
- lib
- vendor
- LICENSE.*
- README.txt
- TODO
- tmp
- node_modules
- gulpfile.js
- package.json
- README.md
- elements.html
- builder
- assets
gems:
  - jekyll-seo-tag
