name: Jamie Tanna
title: Jamie Tanna | Developer
title_short: Jamie Tanna
email: hi@jamietanna.co.uk
image:
  src: profile.png
  alt: Me at Hack24
description: >
    The personal website for Jamie Tanna, a software developer from London.
baseurl: ""
url: ""
username: jamietanna
twitter_username: jamietanna
github_username:  jamietanna
gitlab_username:  jamietanna

# html minify
# compress_html:
#   clippings: all
#   comments: all
#   endings: []
#   profile: false

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge

links:
  - title: home
    url: /
  - title: about me
    url: /about
  - title: my blog
    url: /posts
  - title: my projects
    url: /projects

exclude:
- Gemfile
- Gemfile.lock
- Capfile
- config
- lib
- vendor
- LICENSE.*
- README.txt
- TODO
- tmp
- node_modules
- gulpfile.js
- package.json
- README.md
- elements.html
- builder
- Dockerfile
- src
- log

gems:
  - jekyll-seo-tag
  - jekyll-git_metadata
