name: Jamie Tanna
title: Jamie Tanna | Software (Quality) Engineer
title_short: Jamie Tanna
email: hi@jamietanna.co.uk
image:
  src: /assets/img/profile.png
  alt: Me at Hack24
description: The personal website for Jamie Tanna, a Software (Quality) Engineer based in Nottingham.
long_description:
  - I'm a Software Quality Engineer with a passion for backend engineering, especially with regard to APIs and automation. I've been building up my experience working in a DevOps environment as a Software Development Engineer and am now diving into the details of how we prove out the quality in our software. I use my site as a method of blogging about my learnings, as well as sharing information about projects I have previously, or are currently, working on in my spare time.
  - I'm a GNU/Linux user, a big advocate for the Free Software Movement, and I try to self host my own services where possible, instead of relying on other providers.
baseurl: ""
url: "https://www.jvt.me"
username: jamietanna
author:
  fullname: Jamie Tanna
  gitlab: jamietanna
  github: jamietanna
  twitter: jamietanna
  linkedin: jamietanna
twitter:
  username: jamietanna

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

kramdown:
  input: GFM
  smart_quotes: apos,apos,quot,quot

highlighter: rouge

defaults:
  - values:
      path: ""
    values:
      image: /assets/img/profile.png
  - scope:
      type: "posts"
    values:
      layout: "post"
      toc: true
      is_post: true
      licenses:
        code: Apache-2.0
        prose: CC-BY-NC-SA-4.0

collections:
  projects:
    output: true
  talks:
    output: true

taxonomy:
  tags:
    title: Tags
    description: Blog posts, categorised by tags
    child_title_prefix: 'Tags: '
    child_description_prefix: Blog posts, categorised by the tag
    path: posts/tags
  categories:
    title: Categories
    description: Blog posts, categorised by categories
    child_title_prefix: 'Category: '
    child_description_prefix: Blog posts, categorised by the category
    path: posts/categories
  tech:
    title: Tech
    child_title_prefix: 'Tech: '
    path: projects/tech

jekyll_get:
- data: blogroll
  json: https://blogroll.jvt.me/blogs/index.json
  cache: true

exclude:
- Gemfile
- Gemfile.lock
- Capfile
- config
- lib
- vendor
- LICENSE.*
- README.txt
- TODO
- tmp
- node_modules
- gulpfile.js
- package.json
- README.md
- elements.html
- builder
- Dockerfile
- src
- log
- get_pr.py
- tags
- worktree
- test

plugins:
  - jekyll-seo-tag
  - jekyll-git_metadata
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-spdx_licenses
  - jekyll-toc
