FROM ruby:2.5-alpine
MAINTAINER Jamie Tanna <docker@jamietanna.co.uk>

# Install Ruby {{{
RUN apk --update add git \
		build-base
	# }}}
# }}}

WORKDIR /app
# Ensure we have the latest Ruby dependencies {{{
COPY Gemfile Gemfile.lock /app/
# Don't pull in deploy dependencies as they're a separate Docker image
ENV BUNDLE_WITHOUT=deploy
RUN bundle install
# }}}
# }}}
