FROM alpine:3.5
MAINTAINER Jamie Tanna <docker@jamietanna.co.uk>

WORKDIR "/site"

RUN apk update && \
    apk upgrade && \
	apk add ruby-dev ruby-bundler && \
	apk add git \
		build-base \
		openssh-client

ADD Gemfile /site
ADD Gemfile.lock /site

RUN bundle install --without build test
