FROM klakegg/hugo:0.101.0-ext-alpine
MAINTAINER Jamie Tanna <docker@jamietanna.co.uk>
LABEL me.jvt.www.image-name=hugo-base
LABEL me.jvt.www.version=0.101.0

RUN apk --update --no-cache add git tzdata && \
	cp /usr/share/zoneinfo/Europe/London /etc/localtime && \
	echo 'Europe/London' > /etc/timezone
RUN apk --update --no-cache add aws-cli
ENV HUGO_DESTINATION /public
WORKDIR /site
