FROM ruby:2.5-alpine
MAINTAINER Jamie Tanna <docker@jamietanna.co.uk>
LABEL me.jvt.www.image-name=ruby-base
LABEL me.jvt.www.version=v1

WORKDIR /app
COPY Gemfile Gemfile.lock  /app/
# Don't pull in deploy dependencies as they're a separate Docker image
ENV BUNDLE_WITHOUT=deploy

RUN apk --no-cache --update add git \
		build-base && \
		bundle install
