source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-seo-tag'
gem 'capistrano'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'capistrano-grunt', github: 'roots/capistrano-grunt'
gem 'capistrano-gulp'
gem 'capistrano-npm'
gem 'rouge'
