source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-seo-tag'
gem 'capistrano'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'capistrano-grunt', git: 'https://github.com/roots/capistrano-grunt.git'
gem 'capistrano-gulp'
gem 'capistrano-npm'
gem 'rouge'
